import {
  Video,
  Camera,
  Clapperboard,
  History,
  UserCircle,
  Music,
  Star,
  LayoutGrid,
  Lock,
  MonitorUp,
  ShieldCheck,
  Tv,
  Radio,
  type LucideIcon,
} from "lucide-react";

export interface ToolConfig {
  id: string;
  slug: string;
  title: string;
  shortTitle: string;
  heroTitle: string;
  heroHighlight: string;
  subtitle: string;
  icon: LucideIcon;
  placeholder: string;
  seoTitle: string;
  seoDescription: string;
  features: { title: string; desc: string }[];
  faqs: { q: string; a: string }[];
  seoContent: { title: string; text: string }[];
}

export const tools: ToolConfig[] = [
  {
    id: "video",
    slug: "/",
    title: "Baixar Vídeo do Instagram",
    shortTitle: "Vídeo",
    heroTitle: "Baixar Vídeo",
    heroHighlight: "do Instagram",
    subtitle: "Cole o link e faça baixar vídeo do Instagram gratis instantaneamente em alta qualidade.",
    icon: Video,
    placeholder: "Cole o link do vídeo do Instagram aqui...",
    seoTitle: "Baixar Vídeo do Instagram Online Grátis | Baixar Vídeo Downloader",
    seoDescription: "Baixe vídeos do Instagram em MP4 HD grátis. Ferramenta rápida e segura para salvar vídeos do Instagram no seu dispositivo.",
    features: [
      { title: "MP4 em Alta Qualidade", desc: "Baixe vídeos na resolução original sem perda de qualidade." },
      { title: "Download Instantâneo", desc: "Processamento rápido sem filas de espera." },
      { title: "100% Gratuito", desc: "Sem limites de downloads e sem necessidade de cadastro." },
      { title: "Compatível com Todos", desc: "Funciona em celular, tablet e computador." },
    ],
    faqs: [
      { q: "Como baixar vídeos do Instagram?", a: "Copie o link do vídeo do Instagram, cole no campo acima e clique em 'BAIXAR'. O vídeo será processado e o link de download aparecerá instantaneamente." },
      { q: "Os vídeos são baixados em HD?", a: "Sim! Nosso sistema baixa os vídeos na resolução original disponível no Instagram, geralmente em HD ou Full HD." },
      { q: "Preciso instalar algum aplicativo?", a: "Não! Nossa ferramenta funciona diretamente no navegador, sem necessidade de instalar nenhum app ou extensão." },
      { q: "Posso baixar vídeos de perfis privados?", a: "Não, nossa ferramenta só consegue acessar conteúdos de perfis públicos do Instagram." },
    ],
    seoContent: [
      { title: "Como Funciona o Download de Vídeos", text: "Nossa tecnologia de extração de vídeo garante que você receba o arquivo MP4 original sem compressão adicional. Ideal para criadores de conteúdo e usuários que buscam alta fidelidade visual." },
      { title: "Segurança e Privacidade", text: "Não armazenamos seus dados pessoais nem os vídeos baixados. Todo o processamento é feito de forma segura e os links são temporários." },
    ],
  },
  {
    id: "reels",
    slug: "/baixar-reels-instagram",
    title: "Baixar Reels do Instagram Online Grátis",
    shortTitle: "Reels",
    heroTitle: "Baixar Reels do Instagram",
    heroHighlight: "em HD Sem Marca d'Água",
    subtitle: "Baixe vídeos do Instagram Reels diretamente de qualquer URL pública. Cole o link do Reel abaixo e salve os Reels no seu dispositivo em formato MP4 — alta qualidade, processamento rápido e sem marca d'água.",
    icon: Clapperboard,
    placeholder: "Cole o link do Reel do Instagram aqui...",
    seoTitle: "Baixar Reels do Instagram Online Grátis em HD | Baixar Vídeo Downloader",
    seoDescription: "Baixador de Reels do Instagram Grátis – Cole o Link e Baixe Instantaneamente. Baixe Reels em HD, sem marca d'água, sem login.",
    features: [
      { title: "Velocidade de Download", desc: "Servidores otimizados garantem processamento imediato." },
      { title: "Baixar Reels em HD & 4K", desc: "Mantenha a qualidade e resolução originais." },
      { title: "Seguro e Privado", desc: "Não armazenamos URLs nem dados de usuários." },
      { title: "Baixar Reels com Áudio", desc: "Extraia áudio dos Reels ou converta para MP3 facilmente." },
      { title: "Interface Simples", desc: "Sem anúncios agressivos ou botões enganosos." },
      { title: "100% Grátis e Online", desc: "Downloads ilimitados, sem assinatura." },
    ],
    faqs: [
      { q: "1. Como posso baixar Reels do Instagram online grátis?", a: "Copie o link do Reel, cole no nosso site e clique em baixar." },
      { q: "2. Posso baixar Reels sem marca d'água?", a: "Sim. Nosso site permite baixar Reels sem marca d'água." },
      { q: "3. Posso salvar Reels na galeria?", a: "Sim. O vídeo pode ser salvo diretamente na galeria do celular." },
      { q: "4. Posso baixar Reels em HD ou 4K?", a: "Sim, oferecemos suporte para alta qualidade." },
      { q: "5. Posso baixar Reels com áudio?", a: "Sim. Você pode baixar com áudio original ou converter para MP3." },
      { q: "6. Preciso instalar aplicativo?", a: "Não. É um baixador de Reels online." },
      { q: "7. Posso baixar Reels privados?", a: "Apenas se você tiver acesso autorizado." },
      { q: "8. Funciona no PC e no celular?", a: "Sim. Funciona em Android, iPhone, tablet e desktop." },
    ],
    seoContent: [
      { title: "Download de Reels em Alta Qualidade", text: "Os Reels são o formato de conteúdo mais popular do Instagram. Com nossa ferramenta, você pode salvar qualquer Reel público em MP4 HD com áudio perfeito para assistir offline." },
      { title: "Compatibilidade Universal", text: "Os arquivos MP4 baixados funcionam em qualquer dispositivo e player de mídia, incluindo iPhone, Android, Windows e Mac." },
    ],
  },
  {
    id: "stories",
    slug: "/baixar-stories-instagram",
    title: "Baixar Story do Instagram",
    shortTitle: "Stories",
    heroTitle: "Baixar Stories",
    heroHighlight: "do Instagram",
    subtitle: "Faça baixar story Instagram antes que expire. Também é possível baixar story Instagram privado se você tiver acesso autorizado.",
    icon: History,
    placeholder: "Cole o link do Story do Instagram aqui...",
    seoTitle: "Baixar Stories do Instagram Grátis | Baixar Vídeo Downloader",
    seoDescription: "Salve Stories do Instagram em HD antes que desapareçam. Ferramenta gratuita para baixar Stories de perfis públicos.",
    features: [
      { title: "Salve Antes de Expirar", desc: "Baixe Stories antes que desapareçam em 24 horas." },
      { title: "Vídeo e Foto", desc: "Suporte para Stories em formato de vídeo e imagem." },
      { title: "Qualidade HD", desc: "Download na melhor qualidade disponível." },
      { title: "Anônimo", desc: "Baixe Stories sem que o dono do perfil saiba." },
    ],
    faqs: [
      { q: "Como baixar Stories do Instagram?", a: "Copie o link do Story compartilhável e cole no campo acima. Nosso sistema processará e disponibilizará o download." },
      { q: "Posso baixar Stories de qualquer perfil?", a: "Apenas de perfis públicos. Stories de perfis privados não podem ser acessados por nossa ferramenta." },
      { q: "Os Stories baixados têm boa qualidade?", a: "Sim, baixamos na resolução original que o Instagram disponibiliza." },
      { q: "O dono do perfil sabe que baixei o Story?", a: "Não, o download é feito de forma anônima através do nosso servidor." },
    ],
    seoContent: [
      { title: "Salve Stories Importantes", text: "Stories do Instagram desaparecem após 24 horas. Com nossa ferramenta, você pode salvar aqueles momentos importantes antes que sejam perdidos para sempre." },
      { title: "Download Anônimo e Seguro", text: "Todo o processamento é feito pelos nossos servidores, garantindo que o download seja anônimo e que seus dados permaneçam seguros." },
    ],
  },
  {
    id: "foto",
    slug: "/baixar-fotos-instagram",
    title: "Baixar Foto do Instagram",
    shortTitle: "Fotos",
    heroTitle: "Baixar Fotos",
    heroHighlight: "do Instagram",
    subtitle: "Baixe fotos e carrosséis do Instagram em qualidade original, sem compressão.",
    icon: Camera,
    placeholder: "Cole o link da foto do Instagram aqui...",
    seoTitle: "Baixar Fotos do Instagram em HD Grátis | Baixar Vídeo Downloader",
    seoDescription: "Baixe fotos do Instagram em resolução original HD. Ferramenta gratuita para salvar imagens do Instagram.",
    features: [
      { title: "Resolução Original", desc: "Baixe fotos na resolução máxima disponível no Instagram." },
      { title: "Formato JPG", desc: "Imagens salvas em JPG de alta qualidade." },
      { title: "Download Rápido", desc: "Processamento instantâneo em segundos." },
      { title: "Sem Compressão", desc: "Sem perda de qualidade na imagem baixada." },
    ],
    faqs: [
      { q: "Como baixar fotos do Instagram?", a: "Copie o link da publicação com a foto, cole no campo acima e clique em BAIXAR. A imagem será disponibilizada em resolução original." },
      { q: "A foto é baixada em alta qualidade?", a: "Sim! Baixamos a imagem na resolução original que foi publicada no Instagram." },
      { q: "Posso baixar fotos de carrossel?", a: "Sim, mas para carrossel completo recomendamos usar nossa ferramenta específica de Carrossel." },
      { q: "Funciona em qualquer dispositivo?", a: "Sim, funciona em celulares, tablets e computadores com qualquer navegador." },
    ],
    seoContent: [
      { title: "Fotos em Qualidade Máxima", text: "O Instagram comprime as fotos para exibição na plataforma. Nossa ferramenta extrai a versão de maior resolução disponível, garantindo fotos nítidas e detalhadas." },
      { title: "Ideal para Inspiração", text: "Perfeito para designers, fotógrafos e criadores de conteúdo que precisam salvar referências visuais do Instagram." },
    ],
  },
  {
    id: "profile-picture",
    slug: "/baixar-foto-perfil-instagram",
    title: "Baixar Foto de Perfil do Instagram",
    shortTitle: "Foto de Perfil",
    heroTitle: "Baixar Foto de Perfil",
    heroHighlight: "do Instagram",
    subtitle: "Veja e baixe sua foto de perfil em tamanho real sem precisar fazer login na sua conta.",
    icon: UserCircle,
    placeholder: "Cole o link do perfil do Instagram aqui...",
    seoTitle: "Baixar Foto de Perfil do Instagram em HD | Baixar Vídeo Downloader",
    seoDescription: "Veja e baixe fotos de perfil do Instagram em tamanho completo HD. Amplie e salve a foto de perfil de qualquer usuário público.",
    features: [
      { title: "Tamanho Completo", desc: "Veja a foto de perfil em tamanho grande sem limitações." },
      { title: "Alta Resolução", desc: "Download na maior resolução disponível." },
      { title: "Qualquer Perfil Público", desc: "Funciona com qualquer perfil público do Instagram." },
      { title: "Sem Cadastro", desc: "Use gratuitamente sem precisar criar conta." },
    ],
    faqs: [
      { q: "Como ver a foto de perfil em tamanho grande?", a: "Cole o link do perfil do Instagram e nossa ferramenta irá extrair a foto de perfil em tamanho completo para você visualizar e baixar." },
      { q: "A foto é baixada em boa qualidade?", a: "Sim, extraímos a versão de maior resolução disponível da foto de perfil." },
      { q: "Funciona com perfis privados?", a: "A foto de perfil é sempre pública no Instagram, então funciona com qualquer perfil." },
      { q: "O dono do perfil é notificado?", a: "Não, o download é totalmente anônimo." },
    ],
    seoContent: [
      { title: "Amplie Fotos de Perfil", text: "No Instagram, as fotos de perfil aparecem em tamanho reduzido. Nossa ferramenta permite visualizar e baixar a versão em tamanho completo." },
      { title: "Uso Simples e Rápido", text: "Basta colar o link do perfil e em segundos você terá acesso à foto de perfil em alta resolução." },
    ],
  },
  {
    id: "audio",
    slug: "/extrair-audio-instagram",
    title: "Converter Vídeo do Instagram para MP3",
    shortTitle: "Áudio/MP3",
    heroTitle: "Extrair Áudio",
    heroHighlight: "do Instagram",
    subtitle: "Extraia o áudio de vídeos e Reels do Instagram e converta para formato MP3.",
    icon: Music,
    placeholder: "Cole o link do vídeo/Reel do Instagram aqui...",
    seoTitle: "Extrair Áudio MP3 do Instagram Grátis | Baixar Vídeo Downloader",
    seoDescription: "Extraia áudio de vídeos e Reels do Instagram em MP3. Salve músicas e áudios do Instagram gratuitamente.",
    features: [
      { title: "Extração de Áudio", desc: "Extraia apenas o áudio de qualquer vídeo ou Reel." },
      { title: "Qualidade de Áudio", desc: "Áudio extraído na melhor qualidade disponível." },
      { title: "Músicas e Sons", desc: "Salve músicas, podcasts e efeitos sonoros." },
      { title: "Processo Rápido", desc: "Extração instantânea sem demora." },
    ],
    faqs: [
      { q: "Como extrair áudio de vídeos do Instagram?", a: "Cole o link do vídeo ou Reel e nossa ferramenta extrairá o áudio automaticamente para download." },
      { q: "Em qual formato o áudio é salvo?", a: "O áudio é extraído do vídeo original. O formato depende da fonte, geralmente compatível com todos os players." },
      { q: "Posso extrair áudio de Reels?", a: "Sim! Funciona perfeitamente com Reels, vídeos de feed e IGTV." },
      { q: "A qualidade do áudio é boa?", a: "Sim, o áudio é extraído na qualidade original do vídeo, sem recompressão." },
    ],
    seoContent: [
      { title: "Salve Músicas e Sons", text: "Encontrou uma música incrível em um Reel? Com nossa ferramenta de extração de áudio, você pode salvar o áudio de qualquer vídeo do Instagram." },
      { title: "Uso Pessoal", text: "Ideal para salvar áudios para uso pessoal, como músicas de fundo, podcasts e efeitos sonoros interessantes." },
    ],
  },
  {
    id: "highlights",
    slug: "/baixar-destaques-instagram",
    title: "Baixar Destaques do Instagram",
    shortTitle: "Destaques",
    heroTitle: "Baixar Destaques",
    heroHighlight: "do Instagram",
    subtitle: "Salve Destaques do Instagram em alta qualidade.",
    icon: Star,
    placeholder: "Cole o link dos Destaques do Instagram aqui...",
    seoTitle: "Baixar Destaques (Highlights) do Instagram | Baixar Vídeo Downloader",
    seoDescription: "Baixe Destaques e Highlights do Instagram em HD. Salve coleções inteiras de Highlights de perfis públicos.",
    features: [
      { title: "Highlights Completos", desc: "Baixe Destaques individuais ou coleções completas." },
      { title: "Vídeos e Fotos", desc: "Suporte para todos os tipos de mídia em Destaques." },
      { title: "Alta Qualidade", desc: "Download na resolução original do conteúdo." },
      { title: "Sem Expiração", desc: "Diferente dos Stories, Destaques ficam sempre disponíveis." },
    ],
    faqs: [
      { q: "Como baixar Destaques do Instagram?", a: "Copie o link do Destaque desejado e cole no campo acima. Nosso sistema processará e disponibilizará o download." },
      { q: "Posso baixar todos os Destaques de um perfil?", a: "Você pode baixar cada Destaque individualmente copiando seu respectivo link." },
      { q: "Os Destaques são baixados com qualidade?", a: "Sim, na resolução original disponível no Instagram." },
      { q: "Funciona com perfis privados?", a: "Não, apenas Destaques de perfis públicos podem ser acessados." },
    ],
    seoContent: [
      { title: "Salve Destaques Importantes", text: "Destaques (Highlights) são coleções permanentes de Stories no Instagram. Com nossa ferramenta, você pode baixar e guardar esses conteúdos no seu dispositivo." },
      { title: "Ideal para Pesquisa", text: "Perfeito para quem precisa analisar conteúdo de marcas, influenciadores ou concorrentes." },
    ],
  },
  {
    id: "carousel",
    slug: "/baixar-carrossel-instagram",
    title: "Baixar Post do Instagram (Carrossel)",
    shortTitle: "Carrossel",
    heroTitle: "Baixar Carrossel",
    heroHighlight: "do Instagram",
    subtitle: "Faça baixar post Instagram com múltiplas fotos e vídeos em um único clique.",
    icon: LayoutGrid,
    placeholder: "Cole o link do post carrossel do Instagram aqui...",
    seoTitle: "Baixar Carrossel do Instagram Grátis | Baixar Vídeo Downloader",
    seoDescription: "Baixe todas as imagens e vídeos de posts em carrossel do Instagram. Salve o conteúdo completo do post.",
    features: [
      { title: "Post Completo", desc: "Baixe todas as mídias do carrossel de uma vez." },
      { title: "Fotos e Vídeos", desc: "Suporte para carrossel com mix de fotos e vídeos." },
      { title: "Resolução Original", desc: "Cada arquivo é baixado na qualidade máxima." },
      { title: "Simples de Usar", desc: "Cole o link e baixe todo o conteúdo do post." },
    ],
    faqs: [
      { q: "Como baixar um carrossel completo?", a: "Cole o link do post e nossa ferramenta identificará e disponibilizará o download de todas as mídias do carrossel." },
      { q: "Posso baixar fotos e vídeos misturados?", a: "Sim! Se o carrossel contém fotos e vídeos, todos os formatos serão processados." },
      { q: "Quantas imagens posso baixar por carrossel?", a: "Todos os itens do carrossel serão disponibilizados, independente da quantidade." },
      { q: "A qualidade é mantida?", a: "Sim, cada arquivo é baixado na resolução original do Instagram." },
    ],
    seoContent: [
      { title: "Download de Posts Completos", text: "Posts em carrossel podem conter até 10 fotos e vídeos. Nossa ferramenta processa o link e extrai todas as mídias disponíveis no post." },
      { title: "Perfeito para Criadores", text: "Ideal para criadores de conteúdo que precisam salvar referências de posts bem-sucedidos para inspiração." },
    ],
  },
  {
    id: "private",
    slug: "/baixar-conteudo-privado-instagram",
    title: "Baixar Vídeo e Story Privado do Instagram",
    shortTitle: "Privado",
    heroTitle: "Baixar Conteúdo",
    heroHighlight: "Privado do Instagram",
    subtitle: "Ferramenta para baixar conteúdos privados (com acesso autorizado).",
    icon: Lock,
    placeholder: "Cole o link do conteúdo do Instagram aqui...",
    seoTitle: "Baixar Conteúdo Privado do Instagram | Baixar Vídeo Downloader",
    seoDescription: "Baixe vídeos e fotos de perfis privados do Instagram que você segue. Salve conteúdo privado de forma segura.",
    features: [
      { title: "Perfis que Você Segue", desc: "Acesse conteúdo de perfis privados que você já segue." },
      { title: "Download Seguro", desc: "Seus dados são protegidos durante todo o processo." },
      { title: "Vídeos e Fotos", desc: "Suporte para todos os tipos de mídia privada." },
      { title: "Alta Qualidade", desc: "Download na resolução original do conteúdo." },
    ],
    faqs: [
      { q: "Posso baixar de qualquer perfil privado?", a: "Nossa ferramenta processa links do Instagram. Para conteúdo privado, o link precisa ser acessível. Recomendamos copiar o link diretamente do app quando logado." },
      { q: "É seguro baixar conteúdo privado?", a: "Sim, todo o processamento é feito de forma segura. Não armazenamos seus dados ou credenciais." },
      { q: "Preciso fazer login?", a: "Não é necessário fazer login em nossa ferramenta. Basta colar o link do conteúdo." },
      { q: "Quais formatos são suportados?", a: "Suportamos vídeos (MP4), fotos (JPG) e outros formatos disponíveis no Instagram." },
    ],
    seoContent: [
      { title: "Acesse Conteúdo que Você Segue", text: "Se você já segue um perfil privado e tem acesso ao conteúdo, nossa ferramenta pode ajudá-lo a baixar vídeos e fotos para acesso offline." },
      { title: "Privacidade Garantida", text: "Não solicitamos suas credenciais do Instagram. Todo o processamento é feito através do link que você compartilha." },
    ],
  },
  {
    id: "hd4k",
    slug: "/baixar-hd-4k-instagram",
    title: "Baixar Vídeo Instagram HD / 4K",
    shortTitle: "HD/4K",
    heroTitle: "Baixar em HD/4K",
    heroHighlight: "do Instagram",
    subtitle: "Faça baixar video Instagram HD ou até 4K, mantendo a qualidade original.",
    icon: MonitorUp,
    placeholder: "Cole o link do conteúdo HD do Instagram aqui...",
    seoTitle: "Baixar Instagram em HD 4K Grátis | Baixar Vídeo Downloader",
    seoDescription: "Baixe vídeos e fotos do Instagram em resolução HD e 4K. Qualidade máxima garantida sem compressão.",
    features: [
      { title: "Resolução Máxima", desc: "Baixe na maior resolução disponível, até 4K quando possível." },
      { title: "Sem Compressão", desc: "Download direto sem compressão adicional." },
      { title: "Vídeos e Fotos", desc: "Suporte HD/4K para vídeos e imagens." },
      { title: "Qualidade Profissional", desc: "Ideal para uso profissional e edição." },
    ],
    faqs: [
      { q: "Os vídeos do Instagram estão disponíveis em 4K?", a: "O Instagram suporta vídeos em alta resolução. Nossa ferramenta baixa na maior qualidade disponível, que pode ser HD (1080p) ou superior dependendo do upload original." },
      { q: "As fotos são baixadas em resolução máxima?", a: "Sim! Extraímos a versão de maior resolução que o Instagram disponibiliza para cada imagem." },
      { q: "Qual a diferença para o download normal?", a: "Nossa ferramenta HD/4K prioriza a extração da versão de maior qualidade disponível, ideal para quem precisa de resolução profissional." },
      { q: "Funciona com Reels em HD?", a: "Sim! Reels, vídeos de feed e Stories podem ser baixados em alta definição." },
    ],
    seoContent: [
      { title: "Qualidade Profissional", text: "Para criadores de conteúdo e profissionais que precisam de máxima qualidade, nossa ferramenta HD/4K extrai a versão de maior resolução disponível no Instagram." },
      { title: "Sem Perda de Qualidade", text: "O download é feito diretamente dos servidores do Instagram, sem recompressão ou redução de qualidade." },
    ],
  },
  {
    id: "no-watermark",
    slug: "/baixar-sem-marca-dagua-instagram",
    title: "Baixar Vídeo do Instagram Sem Marca d'Água",
    shortTitle: "Sem Marca d'Água",
    heroTitle: "Baixar sem",
    heroHighlight: "Marca d'Água",
    subtitle: "Salve vídeos limpos para repostagem ou edição.",
    icon: ShieldCheck,
    placeholder: "Cole o link do conteúdo do Instagram aqui...",
    seoTitle: "Baixar Instagram sem Marca d'Água Grátis | Baixar Vídeo Downloader",
    seoDescription: "Baixe vídeos e fotos do Instagram sem marca d'água. Download limpo e em alta qualidade.",
    features: [
      { title: "Sem Marca d'Água", desc: "Download limpo sem logos ou watermarks adicionais." },
      { title: "Conteúdo Original", desc: "O arquivo baixado é idêntico ao original." },
      { title: "Todos os Formatos", desc: "Vídeos, fotos, Reels e Stories sem marcas." },
      { title: "Qualidade Preservada", desc: "Sem alterações na qualidade do arquivo original." },
    ],
    faqs: [
      { q: "O Instagram adiciona marca d'água?", a: "O Instagram não adiciona marcas d'água nos conteúdos. Nossa ferramenta garante que o download seja feito diretamente do arquivo original, sem adições." },
      { q: "Os Reels baixados têm marca d'água?", a: "Quando você baixa pelo nosso site, o Reel vem sem a marca d'água que aparece ao salvar pelo app do Instagram." },
      { q: "A qualidade é afetada?", a: "Não! O arquivo baixado mantém a qualidade original sem nenhuma alteração." },
      { q: "Funciona com todos os tipos de conteúdo?", a: "Sim, vídeos, fotos, Reels, Stories e Destaques são todos baixados sem marcas d'água." },
    ],
    seoContent: [
      { title: "Download Limpo e Profissional", text: "Ao contrário de salvar pelo app do Instagram (que adiciona marca d'água em Reels), nossa ferramenta extrai o arquivo original sem nenhuma adição." },
      { title: "Ideal para Compartilhar", text: "Perfeito para quem quer compartilhar conteúdo em outras plataformas sem marcas d'água visíveis." },
    ],
  },
  {
    id: "igtv",
    slug: "/baixar-igtv-instagram",
    title: "Baixar IGTV do Instagram",
    shortTitle: "IGTV",
    heroTitle: "Baixar IGTV",
    heroHighlight: "do Instagram",
    subtitle: "Baixe vídeos longos do IGTV do Instagram em MP4 HD. Assista offline quando quiser.",
    icon: Tv,
    placeholder: "Cole o link do vídeo IGTV do Instagram aqui...",
    seoTitle: "Baixar IGTV do Instagram Grátis em MP4 HD | Baixar Vídeo Downloader",
    seoDescription: "Baixe vídeos do IGTV do Instagram em MP4 HD grátis. Salve vídeos longos do Instagram no seu dispositivo para assistir offline.",
    features: [
      { title: "Vídeos Longos", desc: "Baixe vídeos de até 60 minutos do IGTV com facilidade." },
      { title: "MP4 em HD", desc: "Download em alta definição no formato MP4 universal." },
      { title: "Áudio Incluído", desc: "Vídeo completo com áudio original sincronizado." },
      { title: "Assista Offline", desc: "Salve e assista quando e onde quiser, sem internet." },
    ],
    faqs: [
      { q: "Como baixar vídeos do IGTV?", a: "Abra o vídeo IGTV no Instagram, copie o link de compartilhamento, cole no campo acima e clique em BAIXAR. O vídeo será processado em segundos." },
      { q: "Os vídeos do IGTV são baixados em HD?", a: "Sim! Nosso sistema extrai o vídeo na maior resolução disponível, geralmente em HD ou Full HD." },
      { q: "Posso baixar vídeos longos do IGTV?", a: "Sim, nossa ferramenta suporta vídeos do IGTV de qualquer duração, desde clipes curtos até vídeos de 60 minutos." },
      { q: "O IGTV ainda existe no Instagram?", a: "Os vídeos do IGTV foram integrados aos vídeos do feed do Instagram. Vídeos longos publicados anteriormente como IGTV continuam disponíveis e podem ser baixados normalmente." },
    ],
    seoContent: [
      { title: "Baixe Vídeos Longos do Instagram", text: "O IGTV foi o formato do Instagram para vídeos longos de até 60 minutos. Embora tenha sido integrado ao feed de vídeos, todo o conteúdo IGTV continua disponível. Com nossa ferramenta, você pode baixar esses vídeos em MP4 HD para assistir offline." },
      { title: "Perfeito para Conteúdo Longo", text: "Ideal para quem quer guardar tutoriais, aulas, workshops, entrevistas e séries de vídeos publicados no IGTV do Instagram." },
    ],
  },
  {
    id: "live",
    slug: "/baixar-live-instagram",
    title: "Baixar Live do Instagram",
    shortTitle: "Live",
    heroTitle: "Baixar Live",
    heroHighlight: "do Instagram",
    subtitle: "Faça download de transmissões ao vivo e salve para assistir depois.",
    icon: Radio,
    placeholder: "Cole o link da Live do Instagram aqui...",
    seoTitle: "Baixar Live do Instagram Grátis | Baixar Vídeo Downloader",
    seoDescription: "Baixe transmissões ao vivo do Instagram em MP4 HD. Salve Lives para assistir depois, quando e onde quiser.",
    features: [
      { title: "Salve Lives", desc: "Baixe transmissões ao vivo do Instagram para assistir depois." },
      { title: "MP4 em HD", desc: "Download em alta definição no formato MP4 universal." },
      { title: "Áudio Incluído", desc: "Vídeo completo com áudio original sincronizado." },
      { title: "Assista Offline", desc: "Salve e assista quando e onde quiser, sem internet." },
    ],
    faqs: [
      { q: "Como baixar Lives do Instagram?", a: "Copie o link da transmissão ao vivo ou da live salva no Instagram, cole no campo acima e clique em BAIXAR." },
      { q: "Posso baixar Lives em andamento?", a: "Lives em andamento podem não estar disponíveis para download. Recomendamos baixar após o término da transmissão, quando o criador salva a live no perfil." },
      { q: "A qualidade da Live é mantida?", a: "Sim, baixamos na resolução original disponível no Instagram." },
      { q: "Funciona com Lives salvas no perfil?", a: "Sim! Lives que o criador salvou no perfil podem ser baixadas normalmente." },
    ],
    seoContent: [
      { title: "Salve Transmissões ao Vivo", text: "Lives do Instagram são momentos únicos que podem ser perdidos. Com nossa ferramenta, você pode baixar lives salvas e assistir quando quiser." },
      { title: "Ideal para Conteúdo Educacional", text: "Perfeito para salvar aulas ao vivo, workshops, entrevistas e eventos transmitidos pelo Instagram Live." },
    ],
  },
];

export function getToolBySlug(slug: string): ToolConfig | undefined {
  return tools.find(t => t.slug === slug);
}

export function getToolById(id: string): ToolConfig | undefined {
  return tools.find(t => t.id === id);
}

export const toolsExceptMain = tools.filter(t => t.slug !== "/");
